name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v1
    - name: Run the tests
      run: |
        # Fail as soon as any error has occured
        set -e
        # Print commands as they are being executed
        set -x
        # Run all test scripts
        cd test
        npm install
        for d in */ ;
        do
          if [ $d = "node_modules/" ]; then
            continue
          fi

          echo $d
          cd $d
          node .
          cd ..
        done
